import def_test_original
from def_test_original import model_test
import def_test
from def_test import model_test
import ot_curve
from ot_curve import curve
import numpy as np
import os
import re
import torch
import torch.optim as optim
from torch import tensor
from torch.utils.data import Dataset, DataLoader
import json
from transformers import BartForConditionalGeneration, BartTokenizer, BartModel, AutoModel
from transformers.utils.import_utils import SENTENCEPIECE_IMPORT_ERROR

# inputs
test_data_path = '/home/yiwang/Datasets/test'
test_batch_size = 32
model_save_path = '/home/yiwang/Datasets/model/train6.pth'
test_max_length = 80

print('-- generated by model:',model_save_path)

original_model_result = def_test_original.model_test(test_data_path,
     test_batch_size,
     test_max_length
     )

trained_model_result = def_test.model_test(test_data_path,
        test_batch_size,
        model_save_path,
        test_max_length)

ot_curve.curve(original_model_result, trained_model_result)
