import testing_set
from testing_set import trained_model_BLEU, trained_model_bert, original_model_BLEU, original_model_bert
import Plots_creater
from Plots_creater import OT_plot, result_means
import numpy as np
import os
import re
import torch
import torch.optim as optim
from torch import tensor
from torch.utils.data import Dataset, DataLoader
import json

import transformers_len.src.transformers.models.bart.modeling_bart
from transformers_len.src.transformers.models.bart.modeling_bart import BartForConditionalGeneration, BartModel
import transformers_len.src.transformers.models.bart.tokenization_bart
from transformers_len.src.transformers.models.bart.tokenization_bart import BartTokenizer
from transformers.utils.import_utils import SENTENCEPIECE_IMPORT_ERROR

# inputs
test_data_path = '/home/yiwang/Datasets/sc/normal/test'
test_batch_size = 32
model_save_path = '/home/yiwang/Datasets/model/LA/sc_normal_8_32_160_e-5.pth'
test_max_length = 160

print('-- generated by model:',model_save_path)

#original_model_result,original_model_means,source_len,output_len,reference_len = testing_set.original_model_BLEU(test_data_path,
#     test_batch_size,
#     test_max_length
#     )
#,source_len,output_len,reference_len
trained_model_result,trained_model_means = testing_set.trained_model_bert(test_data_path,
        test_batch_size,
        model_save_path,
        test_max_length
        )
#train_result = np.array(trained_model_result)
#np.save('train_result.npy',train_result)

#print('-----trained-----')
#print(type(trained_model_result))
#print(type(trained_model_means))
#print(trained_model_result)
print(trained_model_means)
#print('-----original-----')
#print(type(original_model_result))
#print(type(original_model_means))
#print(original_model_result)
#print(original_model_means)

#trained_model_result = np.array(trained_model_result)
#np.save('/home/yiwang/Datasets/figure_config/LA/Quora/normal/10_64_80_e-5/BLEU/trained_model_result.npy',trained_model_result)
#trained_model_means = np.array(trained_model_means)
#np.save('/home/yiwang/Datasets/figure_config/LA/Quora/normal/10_64_80_e-5/BLEU/trained_model_means.npy',trained_model_means)
#original_model_result = np.array(original_model_result)
#np.save('/home/yiwang/Datasets/figure_config/LA/sc/normal/1_50_160_6e-5/BLEU/original_model_result.npy',original_model_result)
#original_model_means = np.array(original_model_means)
#np.save('/home/yiwang/Datasets/figure_config/LA/sc/normal/1_50_160_6e-5/BLEU/original_model_means.npy',original_model_means)
#source_len = np.array(source_len)
#np.save('/home/yiwang/Datasets/figure_config/LA/sc/normal/8_32_160_e-5/source_len.npy',source_len)
#output_len = np.array(output_len)
#np.save('/home/yiwang/Datasets/figure_config/LA/sc/normal/8_32_160_e-5/output_len.npy',output_len)
#reference_len = np.array(reference_len)
#np.save('/home/yiwang/Datasets/figure_config/LA/sc/normal/8_32_160_e-5/reference_len.npy',reference_len)

print('finish evaluation about model:',model_save_path)
